name: Terraform Preview

on:
  pull_request:
    branches:
      - main

jobs:
  preview:
    name: Plan Terraform changes
    runs-on: ubuntu-latest
    env:
      CIVO_ACCESS_KEY: ${{ secrets.CIVO_ACCESS_KEY }}
      CIVO_SECRET_KEY: ${{ secrets.CIVO_SECRET_KEY }}
      CIVO_TOKEN: ${{ secrets.CIVO_TOKEN }}

    permissions:
      id-token: write
      contents: read
      pull-requests: write
      checks: read

    strategy:
      fail-fast: false
      matrix:
        include:
          - env: dev
            region: lon1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install asdf
        uses: asdf-vm/actions/setup@v3
        with:
          asdf_branch: v0.15.0

      - name: Install OpenTofu with asdf
        run: |
          asdf plugin add opentofu
          asdf install opentofu

      - name: Install Terragrunt with asdf
        run: |
          asdf plugin add terragrunt
          asdf install terragrunt

      - name: Check Terraform formatting
        run: tofu fmt -recursive -check -diff

      - name: Terragrunt init
        working-directory: environments/${{ matrix.region }}/${{ matrix.env }}
        run: terragrunt init

      - name: Terragrunt plan
        working-directory: environments/${{ matrix.region }}/${{ matrix.env }}
        run: terragrunt plan
